<?php

namespace App\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPending()
    {
        return (int) $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->where('c.approved = :approved')
            ->setParameter('approved', false)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findPendingNotifications($limit = 5)
    {
        return $this->createQueryBuilder('c')
            ->where('c.approved = :approved')
            ->setParameter('approved', false)
            ->orderBy('c.createdAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
    public function getApprovedCommentsForNews($newsId)
    {
        return $this->createQueryBuilder('c')
            ->where('c.news_id = :news_id')
            ->andWhere('c.approved = :approved')
            ->setParameter('news_id', $newsId)
            ->setParameter('approved', 1)
            ->getQuery()->getResult();
    }
}
