<?php

namespace App\Repository;

use App\Entity\News;
use App\Entity\User;
use App\Enum\PostStatus;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, News::class);
    }

    public function findAllPosts(?User $author = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->setParameter('postType', 'post')
            ->orderBy('n.createdAt', 'DESC');

        if (null !== $author) {
            $qb->andWhere('n.author = :author')->setParameter('author', $author);
        }

        return $qb->getQuery()->getResult();
    }

    public function findAllPages()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM App\Entity\News n WHERE n.postType = :postType ORDER BY n.parent ASC, n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function findPagesAsTree()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM App\Entity\News n WHERE n.postType = :postType AND n.parent IS NULL ORDER BY n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function searchPages($query)
    {
        return $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )
            ->setParameter('postType', 'page')
            ->setParameter('query', '%'.$query.'%')
            ->orderBy('n.title', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function searchPosts($query, $categoryId = null, ?User $author = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )
            ->setParameter('postType', 'post')
            ->setParameter('query', '%'.$query.'%')
            ->orderBy('n.createdAt', 'DESC');

        if (null !== $categoryId) {
            $qb
                ->leftJoin('n.category', 'c')
                ->andWhere('c.id = :categoryId')
                ->setParameter('categoryId', $categoryId);
        }

        if (null !== $author) {
            $qb->andWhere('n.author = :author')->setParameter('author', $author);
        }

        return $qb->getQuery()->getResult();
    }

    public function getNewsByCategories($categoryIds, $orderBy, $orderDir, $limit = null) {
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.category', 't')
            ->where('t.id IN (:categoryIds)')
            ->andWhere('n.status = :status')
            ->setParameter('categoryIds', $categoryIds)
            ->setParameter('status', PostStatus::Published)
            ->orderBy('n.' . $orderBy, $orderDir);
            
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getNewsByCategory($categoryId, $orderBy, $orderDir, $limit = null) {
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.category', 't')
            ->where('t.id = :categoryId')
            ->andWhere('n.status = :status')
            ->setParameter('categoryId', $categoryId)
            ->setParameter('status', PostStatus::Published)
            ->orderBy('n.' . $orderBy, $orderDir);
            
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getRelatedNews($categoryId, $excludeId, $postType, $orderBy, $orderDir, $limit = 12) {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.category', 't')
            ->where('t.id = :categoryId')
            ->andWhere('r.id <> :id')
            ->andWhere('r.postType = :postType')
            ->andWhere('r.status = :status')
            ->setParameter('categoryId', $categoryId)
            ->setParameter('id', $excludeId)
            ->setParameter('postType', $postType)
            ->setParameter('status', PostStatus::Published)
            ->setMaxResults($limit)
            ->orderBy('r.' . $orderBy, $orderDir)
            ->getQuery()
            ->getResult();
    }

    public function getNewsByTag($tagId, $limit = 40) {
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.tags', 't')
            ->where('t.id = :tagId')
            ->andWhere('n.status = :status')
            ->setParameter('tagId', $tagId)
            ->setParameter('status', PostStatus::Published)
            ->orderBy('n.createdAt', 'DESC');
            
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }
}
