<?php

namespace App\Repository;

/**
 * NewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubCategories($parentId)
    {
        return $this->createQueryBuilder('c')
            ->where('c.parentcat = :parentcat')
            ->setParameter('parentcat', $parentId)
            ->getQuery()
            ->getResult();
    }
}
