<?php

namespace App\Repository;

use App\Entity\News;
use App\Entity\User;
use App\Enum\PostStatus;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, News::class);
    }

    public function findAllPosts(?User $author = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->setParameter('postType', 'post')
            ->orderBy('n.createdAt', 'DESC');

        if (null !== $author) {
            $qb->andWhere('n.author = :author')->setParameter('author', $author);
        }

        return $qb;
    }

    /**
     * Danh sách bài viết admin: lọc theo từ khóa, trạng thái và danh mục cùng lúc.
     * Join danh mục chỉ để lọc (không addSelect) — xem ghi chú ở getNewsByCategories().
     *
     * @param array{q?: string, status?: ?PostStatus, category?: ?int} $filters
     */
    public function filterPosts(array $filters, ?User $author = null)
    {
        $qb = $this->findAllPosts($author);

        if (($filters['q'] ?? '') !== '') {
            $qb->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )->setParameter('query', '%'.addcslashes($filters['q'], '%_').'%');
        }
        if (null !== ($filters['status'] ?? null)) {
            $qb->andWhere('n.status = :status')->setParameter('status', $filters['status']);
        }
        if (null !== ($filters['category'] ?? null)) {
            $qb->innerJoin('n.category', 'fc')
                ->andWhere('fc.id = :categoryId')
                ->setParameter('categoryId', $filters['category']);
        }

        return $qb;
    }

    /**
     * Số bài viết theo trạng thái, dạng [status value => count].
     *
     * @return array<string, int>
     */
    public function countPostsByStatus(?User $author = null): array
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n.status AS status, COUNT(n.id) AS total')
            ->where('n.postType = :postType')
            ->setParameter('postType', 'post')
            ->groupBy('n.status');

        if (null !== $author) {
            $qb->andWhere('n.author = :author')->setParameter('author', $author);
        }

        $counts = [];
        foreach ($qb->getQuery()->getArrayResult() as $row) {
            $status = $row['status'] instanceof PostStatus ? $row['status']->value : (string) $row['status'];
            $counts[$status] = (int) $row['total'];
        }

        return $counts;
    }

    public function findAllPages()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM App\Entity\News n WHERE n.postType = :postType ORDER BY n.parent ASC, n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function findPagesAsTree()
    {
        return $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere('n.parent IS NULL')
            ->setParameter('postType', 'page')
            ->orderBy('n.title', 'ASC');
    }

    public function searchPages($query)
    {
        return $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )
            ->setParameter('postType', 'page')
            ->setParameter('query', '%'.$query.'%')
            ->orderBy('n.title', 'ASC');
    }

    public function searchPosts($query, $categoryId = null, ?User $author = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )
            ->setParameter('postType', 'post')
            ->setParameter('query', '%'.$query.'%')
            ->orderBy('n.createdAt', 'DESC');

        if (null !== $categoryId) {
            $qb
                ->leftJoin('n.category', 'c')
                ->andWhere('c.id = :categoryId')
                ->setParameter('categoryId', $categoryId);
        }

        if (null !== $author) {
            $qb->andWhere('n.author = :author')->setParameter('author', $author);
        }

        return $qb;
    }

    // 4 method dưới đây join category/tags CHỈ để lọc (t.id IN/=), không
    // addSelect('t') — cố ý. Nếu addSelect thẳng vào join lọc này, collection
    // category/tags mỗi News sẽ chỉ chứa phần tử KHỚP điều kiện lọc chứ không
    // phải toàn bộ category/tag thật của bài viết đó — sai dữ liệu khi có bài
    // gán nhiều category. Đã kiểm tra: không có template nào đang gọi
    // post.getCategory()/post.getTags() trên kết quả các hàm này (chỉ dùng
    // title/ảnh/mô tả/ngày), nên hiện không có N+1 thật xảy ra. Nếu sau này
    // cần hiển thị category/tag trên các danh sách này, phải thêm 1 join
    // KHÔNG điều kiện riêng (leftJoin + addSelect) chứ không tái dùng join lọc.
    public function getNewsByCategories($categoryIds, $orderBy, $orderDir, $limit = null) {
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.category', 't')
            ->where('t.id IN (:categoryIds)')
            ->andWhere('n.status = :status')
            ->setParameter('categoryIds', $categoryIds)
            ->setParameter('status', PostStatus::Published)
            ->orderBy('n.' . $orderBy, $orderDir);
            
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getNewsByCategory($categoryId, $orderBy, $orderDir, $limit = null) {
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.category', 't')
            ->where('t.id = :categoryId')
            ->andWhere('n.status = :status')
            ->setParameter('categoryId', $categoryId)
            ->setParameter('status', PostStatus::Published)
            ->orderBy('n.' . $orderBy, $orderDir);
            
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    public function getRelatedNews($categoryId, $excludeId, $postType, $orderBy, $orderDir, $limit = 12) {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.category', 't')
            ->where('t.id = :categoryId')
            ->andWhere('r.id <> :id')
            ->andWhere('r.postType = :postType')
            ->andWhere('r.status = :status')
            ->setParameter('categoryId', $categoryId)
            ->setParameter('id', $excludeId)
            ->setParameter('postType', $postType)
            ->setParameter('status', PostStatus::Published)
            ->setMaxResults($limit)
            ->orderBy('r.' . $orderBy, $orderDir)
            ->getQuery()
            ->getResult();
    }

    public function getNewsByTag($tagId, $limit = 40) {
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.tags', 't')
            ->where('t.id = :tagId')
            ->andWhere('n.status = :status')
            ->setParameter('tagId', $tagId)
            ->setParameter('status', PostStatus::Published)
            ->orderBy('n.createdAt', 'DESC');
            
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }
}
