<?php

namespace App\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAverageRatingForNews($newsId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT AVG(r.rating) as ratingValue, COUNT(r) as ratingCount
                FROM \App\Entity\Rating r
                WHERE r.news_id = :news_id'
            )->setParameter('news_id', $newsId)
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
