parameters:
    locale: vi
    app.cache_version: '%env(CACHE_VERSION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\Persistence\ObjectManager: '@doctrine.orm.entity_manager'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php,EventListener/RedirectToPreferredLocaleSubscriber.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\ListUsersCommand:
        arguments:
            $emailSender: '%app.notifications.email_sender%'

    App\Twig\AppExtension:
        arguments:
            $locales: '%app_locales%'
            $doctrine: '@doctrine'
            $authorizationChecker: '@security.authorization_checker'

    # App\EventListener\RedirectToPreferredLocaleSubscriber:
    #     arguments:
    #         $locales: '%app_locales%'
    #         $defaultLocale: '%locale%'

    App\Utils\Slugger:
        public: true

    convertImages:
        alias: App\Utils\ConvertImages
        public: true

    settings_manager:
        alias: App\Service\SettingsManager
        public: true


    app.menu_service:
        class: App\Service\MenuService
        arguments: ['@doctrine.orm.entity_manager']

    App\Twig\MenuExtension:
        arguments: ['@app.menu_service']
        tags:
            - { name: twig.extension }

    App\Service\ActivityLogService:
        public: true
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $tokenStorage: '@security.token_storage'
            $requestStack: '@request_stack'

    App\Service\ViewCountLogger:
        arguments:
            $logDir: '%kernel.logs_dir%'

    App\Command\SyncViewCountsCommand:
        arguments:
            $logsDir: '%kernel.logs_dir%'

    App\EventListener\LoginListener:
        arguments:
            $activityLogService: '@App\Service\ActivityLogService'
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onSecurityInteractiveLogin' }
            - { name: 'kernel.event_listener', event: 'Symfony\Component\Security\Http\Event\LoginFailureEvent', method: 'onLoginFailure' }
